; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32dev]
platform = https://github.com/platformio/platform-espressif32.git
board = esp32dev
framework = arduino

board_build.filesystem = littlefs
board_build.partitions = huge_app.csv

; Serial Monitor Baud Rate
monitor_speed = 115200
monitor_filters = esp32_exception_decoder

upload_port = /dev/ttyUSB0
monitor_port = /dev/ttyUSB0

; ; USB CDC, PSRAM Flags, and WebServer Conflict Blockers
build_flags = 
  -std=gnu++17
  -D CATFEEDER_VERSION=\"1.0.0\" 

lib_deps = 
	esp32async/ESPAsyncWebServer@^3.11.2